restrict_kubeapi: []
# newly introduced:
openstack_loadbalancer_apiserver: false
# TBD, currently needed:
images:
  controlPlane:
    name: ubuntu-capi-image-v1.33.4
  worker:
    name: ubuntu-capi-image-v1.33.4
identityRef:
  name: openstack
  cloudName: openstack
