apiVersion: v2
dependencies:
  - alias: metrics-server
    name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.2
  - alias: cilium
    name: cilium
    repository: https://helm.cilium.io/
    version: 1.16.7
name: docker-scs-1-30-cluster-addon
type: application
version: v1
