apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
    machineInfrastructure:
      ref:
        kind: Metal3MachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3ClusterTemplate
      name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
  workers:
    machineDeployments:
    - class: {{ .Release.Name }}-{{ .Chart.Version }}
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: {{ .Release.Name }}-{{ .Chart.Version }}
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: Metal3MachineTemplate
            name: {{ .Release.Name }}-{{ .Chart.Version }}
  variables:
  - name: controlPlaneEndpoint
    required: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          host:
            type: string
          port:
            type: integer
            default: 6443
        required:
        - host
  - name: image
    schema:
      openAPIV3Schema:
        type: object
        properties:
          checksum:
            type: string
          checksumType:
            type: string
            enum:
            - md5
            - sha256
            - sha512
          format:
            type: string
            enum:
            - raw
            - qcow2
            - vdi
            - vmdk
            - live-iso
          url:
            type: string
        required:
        - checksum
        - url
  - name: user
    schema:
      openAPIV3Schema:
        type: object
        properties:
          name:
            type: string
          sshKey:
            type: string
        required:
        - name
        - sshKey
  - name: workerDataTemplate
    schema:
      openAPIV3Schema:
        type: string
  - name: controlPlaneDataTemplate
    schema:
      openAPIV3Schema:
        type: string
  - name: workerHostSelector
    schema:
      openAPIV3Schema:
        type: object
        properties:
          matchLabels:
            type: object
            additionalProperties:
              type: string
          matchExpressions:
            type: array
            items:
              type: object
              properties:
                key:
                  type: string
                operator:
                  type: string
                values:
                  type: array
                  items:
                    type: string
              required:
              - key
              - operator
              - values
  - name: controlPlaneHostSelector
    schema:
      openAPIV3Schema:
        type: object
        properties:
          matchLabels:
            type: object
            additionalProperties:
              type: string
          matchExpressions:
            type: array
            items:
              type: object
              properties:
                key:
                  type: string
                operator:
                  type: string
                values:
                  type: array
                  items:
                    type: string
              required:
              - key
              - operator
              - values
  patches:
  - name: controlPlaneEndpoint
    description: Adds controlPlaneEndpoint data of Metal3ClusterTemplate used by the cluster
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3ClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/controlPlaneEndpoint
        valueFrom:
          variable: controlPlaneEndpoint
  - name: kube_vip
    description: Adds kube-vip
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/files/-"
        valueFrom:
          template: |
            content: |
              apiVersion: v1
              kind: Pod
              metadata:
                creationTimestamp: null
                name: kube-vip
                namespace: kube-system
              spec:
                containers:
                - args:
                  - manager
                  env:
                  - name: vip_arp
                    value: "true"
                  - name: port
                    value: '{{"{{"}} .controlPlaneEndpoint.port {{"}}"}}'
                  - name: vip_cidr
                    value: "32"
                  - name: dns_mode
                    value: first
                  - name: cp_enable
                    value: "true"
                  - name: cp_namespace
                    value: kube-system
                  - name: svc_enable
                    value: "true"
                  - name: svc_leasename
                    value: plndr-svcs-lock
                  - name: svc_election
                    value: "true"
                  - name: vip_leaderelection
                    value: "true"
                  - name: vip_leasename
                    value: plndr-cp-lock
                  - name: vip_leaseduration
                    value: "5"
                  - name: vip_renewdeadline
                    value: "3"
                  - name: vip_retryperiod
                    value: "1"
                  - name: lb_enable
                    value: "true"
                  - name: lb_port
                    value: '{{"{{"}} .controlPlaneEndpoint.port {{"}}"}}'
                  - name: lb_fwdmethod
                    value: local
                  - name: address
                    value: '{{"{{"}} .controlPlaneEndpoint.host {{"}}"}}'
                  - name: prometheus_server
                    value: :2112
                  image: ghcr.io/kube-vip/kube-vip:v0.7.2
                  imagePullPolicy: IfNotPresent
                  name: kube-vip
                  resources: {}
                  securityContext:
                    capabilities:
                      add:
                      - NET_ADMIN
                      - NET_RAW
                  volumeMounts:
                  - mountPath: /etc/kubernetes/admin.conf
                    name: kubeconfig
                hostAliases:
                - hostnames:
                  - kubernetes
                  ip: 127.0.0.1
                hostNetwork: true
                volumes:
                - hostPath:
                    path: /etc/kubernetes/admin.conf
                  name: kubeconfig
              status: {}
            owner: "root:root"
            path: /etc/kubernetes/manifests/kube-vip.yaml
            permissions: "0644"
  - name: image
    description: Overrides image data for worker and control plane nodes
    enabledIf: {{ `"{{ if .image }}true{{end}}"` }}
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
          machineDeploymentClass:
            names:
            - {{ .Release.Name }}-{{ .Chart.Version }}
      jsonPatches:
      - op: replace
        path: /spec/template/spec/image/checksum
        valueFrom:
          variable: image.checksum
      - op: replace
        path: /spec/template/spec/image/checksumType
        valueFrom:
          variable: image.checksumType
      - op: replace
        path: /spec/template/spec/image/format
        valueFrom:
          variable: image.format
      - op: replace
        path: /spec/template/spec/image/url
        valueFrom:
          variable: image.url
  - name: user
    description: Adds user with ssh access to worker and control plane nodes
    enabledIf: {{ `"{{ if .user }}true{{end}}"` }}
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/users"
        valueFrom:
          template: |
            - name: '{{"{{"}} .user.name {{"}}"}}'
              sshAuthorizedKeys:
              - '{{"{{"}} .user.sshKey {{"}}"}}'
              sudo: ALL=(ALL) NOPASSWD:ALL
    - selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - {{ .Release.Name }}-{{ .Chart.Version }}
      jsonPatches:
      - op: add
        path: "/spec/template/spec/users"
        valueFrom:
          template: |
            - name: '{{"{{"}} .user.name {{"}}"}}'
              sshAuthorizedKeys:
              - '{{"{{"}} .user.sshKey {{"}}"}}'
              sudo: ALL=(ALL) NOPASSWD:ALL
  - name: workerDataTemplate
    description: Adds data-template for worker nodes
    enabledIf: {{ `"{{ if .workerDataTemplate }}true{{end}}"` }}
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - {{ .Release.Name }}-{{ .Chart.Version }}
      jsonPatches:
      - op: add
        path: /spec/template/spec/dataTemplate
        valueFrom:
          template: |
            name: {{"{{"}} .workerDataTemplate {{"}}"}}
  - name: controlPlaneDataTemplate
    description: Adds data-template for control plane nodes
    enabledIf: {{ `"{{ if .controlPlaneDataTemplate }}true{{end}}"` }}
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/dataTemplate
        valueFrom:
          template: |
            name: {{"{{"}} .controlPlaneDataTemplate {{"}}"}}
  - name: workerHostSelector
    description: Adds baremetal host selector for worker nodes
    enabledIf: {{ `"{{ if .workerHostSelector }}true{{end}}"` }}
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - {{ .Release.Name }}-{{ .Chart.Version }}
      jsonPatches:
      - op: add
        path: /spec/template/spec/hostSelector
        valueFrom:
          variable: workerHostSelector
  - name: controlPlaneHostSelector
    description: Adds baremetal host selector for control plane nodes
    enabledIf: {{ `"{{ if .controlPlaneHostSelector }}true{{end}}"` }}
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/hostSelector
        valueFrom:
          variable: controlPlaneHostSelector
