apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{"{{"}} ds.meta_data.hostname {{"}}"}}'
