apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3ClusterTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
spec:
  template:
    spec:
      noCloudProvider: true
