apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-default-worker
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      image:
        url: {{ .Values.image.url }}
        checksum: {{ .Values.image.checksum }}
        checksumType: {{ .Values.image.checksumType }}
        format: {{ .Values.image.format }}
