apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackClusterTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
spec:
  template:
    spec:
      allowAllInClusterTraffic: true
      cloudName: {{ default "openstack" .Values.cloud.name }}
      identityRef:
        name: {{ default "openstack" .Values.secrets.clouds_yaml }}
        kind: Secret
      disableAPIServerFloatingIP: true
      apiServerLoadBalancer:
        enabled: false
      managedSecurityGroups: true
      externalNetworkId: {{ .Values.external_id }}
