apiVersion: v2
dependencies:
  - alias: metrics-server
    name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.2
  - alias: cilium
    name: cilium
    repository: https://helm.cilium.io/
    version: 1.16.3
  - alias: openstack-cloud-controller-manager
    name: openstack-cloud-controller-manager
    repository: https://kubernetes.github.io/cloud-provider-openstack
    version: 2.28.4
  - alias: openstack-cinder-csi
    name: openstack-cinder-csi
    repository: https://kubernetes.github.io/cloud-provider-openstack
    version: 2.28.2
  - alias: yawol-controller
    condition: yawol-controller.enabled
    name: yawol-controller
    repository: https://stackitcloud.github.io/yawol
    version: 0.25.0
name: openstack-scs-1-29-cluster-addon
type: application
version: v1
