# mirrored from variables.tf
controller_flavor: SCS-2V-4-20
worker_flavor: SCS-2V-4-20
restrict_kubeapi: []

# newly introduced:
openstack_loadbalancer_apiserver: false

# TBD, currently needed:
images:
  controlPlane:
    name: ubuntu-capi-image-v1.31.2
  worker:
    name: ubuntu-capi-image-v1.31.2
node_cidr: 10.8.0.0/20
openstack_loadbalancer_apiserver: false
restrict_kubeapi: []
worker_flavor: SCS-2V-4-20
