controller_flavor: SCS-2V-4-20s
identityRef:
  cloudName: openstack
  name: openstack
images:
  controlPlane:
    name: ubuntu-capi-image-v1.31.5
  worker:
    name: ubuntu-capi-image-v1.31.5
openstack_loadbalancer_apiserver: false
restrict_kubeapi: []
worker_flavor: SCS-2V-4-20
