# mirrored from variables.tf
dns_nameservers:
  - 5.1.66.255
  - 185.150.99.255
controller_flavor: SCS-2V-4-20
worker_flavor: SCS-2V-4-20
node_cidr: 10.8.0.0/20
restrict_kubeapi: []

# newly introduced:
openstack_loadbalancer_apiserver: true

# TBD, currently needed:
images:
  controlPlane:
    name: ubuntu-capi-image-v1.28.11
  worker:
    name: ubuntu-capi-image-v1.28.11
identityRef:
  name: openstack
  cloudName: openstack
