# mirrored from variables.tf
controller_flavor: SCS-2V-4-20
worker_flavor: SCS-2V-4-20
restrict_kubeapi: []

# newly introduced:
openstack_loadbalancer_apiserver: true

# TBD, currently needed:
images:
  controlPlane:
    name: ubuntu-capi-image-v1.29.9
  worker:
    name: ubuntu-capi-image-v1.29.9
identityRef:
  name: openstack
  cloudName: openstack
