controller_flavor: SCS-2V-4-20
dns_nameservers:
- 5.1.66.255
- 185.150.99.255
external_id: ebfe5546-f09f-4f42-ab54-094e457d42ec
identityRef:
  cloudName: openstack
  name: openstack
images:
  controlPlane:
    name: ubuntu-capi-image-v1.29.6
  worker:
    name: ubuntu-capi-image-v1.29.6
node_cidr: 10.8.0.0/20
openstack_loadbalancer_apiserver: true
restrict_kubeapi: []
worker_flavor: SCS-2V-4-20
