# mirrored from variables.tf
controller_flavor: SCS-2V-4-20s
worker_flavor: SCS-2V-4-20
restrict_kubeapi: []
# newly introduced:
openstack_loadbalancer_apiserver: false
# TBD, currently needed:
images:
  controlPlane:
    name: ubuntu-capi-image-v1.30.11
  worker:
    name: ubuntu-capi-image-v1.30.11
identityRef:
  name: openstack
  cloudName: openstack
