controller_flavor: SCS-2V-4-20
dns_nameservers:
- 5.1.66.255
- 185.150.99.255
identityRef:
  cloudName: openstack
  name: openstack
images:
  controlPlane:
    name: ubuntu-capi-image-v1.29.10
  worker:
    name: ubuntu-capi-image-v1.29.10
node_cidr: 10.8.0.0/20
openstack_loadbalancer_apiserver: false
restrict_kubeapi: []
worker_flavor: SCS-2V-4-20
