apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{.Release.Namespace}}
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: {{ .Chart.Name }}-{{ .Chart.Version }}-docker-control-plane
      namespace: {{ .Release.Namespace }}
    machineInfrastructure:
      ref:
        kind: DockerMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: {{ .Chart.Name }}-{{ .Chart.Version }}-docker-machine
        namespace: {{ .Release.Namespace }}
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerClusterTemplate
      name: {{ .Chart.Name }}-{{ .Chart.Version }}-docker-cluster
      namespace: {{ .Release.Namespace }}
  workers:
    machineDeployments:
    - class: worker-docker-amd64
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: {{ .Chart.Name }}-{{ .Chart.Version }}-docker-worker-bootstrap-config
            namespace: {{ .Release.Namespace }}
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: DockerMachineTemplate
            name: {{ .Chart.Name }}-{{ .Chart.Version }}-docker-machine
            namespace: {{ .Release.Namespace }}
  variables:
  - name: imageRepository
    required: true
    schema:
      openAPIV3Schema:
        type: string
        default: ""
        example: "registry.k8s.io"
        description: "imageRepository sets the container registry to pull images from. If empty, nothing will be set and the from of kubeadm will be used."
  patches:
  - name: imageRepository
    description: "Sets the imageRepository used for the KubeadmControlPlane."
    enabledIf: '{{ ne .imageRepository "" }}'
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/clusterConfiguration/imageRepository"
        valueFrom:
          variable: imageRepository
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/initConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver"
        value: cgroupfs
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/joinConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver"
        value: cgroupfs
    definitions:
    - selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - worker-docker-amd64
      jsonPatches:
      - op: add
        path: "/spec/template/spec/joinConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver"
        value: cgroupfs
  - name: customImage
    description: "Sets the container image that is used for running dockerMachines for the controlPlane and worker-docker-amd64 machineDeployments."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - worker-docker-amd64
      jsonPatches:
      - op: add
        path: "/spec/template/spec/customImage"
        value: {{ (index .Values.images.controlPlane 0).name }}:dev
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/customImage"
        value: {{ (index .Values.images.controlPlane 0).name }}:dev
  - name: DockerMachineTemplateWorker
    description: "Sets the container image that is used for running dockerMachines for the worker machineDeployments."
    definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: DockerMachineTemplate
          matchResources:
            machineDeploymentClass:
              names:
                - worker-docker-amd64
        jsonPatches:
          - op: add
            path: "/spec/template/spec/customImage"
            value: {{ (index .Values.images.worker 0).name }}:dev
