openstack-cloud-controller-manager:
  secret:
    enabled: true
    name: ccm-cloud-config
    create: true
  #nodeSelector:
  ## Added by KG: Move to control plane
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
      effect: NoSchedule
    ## Added by KG
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  # Allow DNS resolution before CoreDNS is up
  hostNetwork: true
  # dnsPolicy: ClusterFirstWithHostNet
  dnsPolicy: Default
  extraVolumes:
    - name: clouds-yaml
      secret:
        secretName: clouds-yaml
  extraVolumeMounts:
    - name: clouds-yaml
      readOnly: true
      mountPath: /etc/openstack
  cloudConfig:
    global:
      use-clouds: true
