apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: docker-ferrol-1-26-v1
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
      - name: imageRepository
        value: ""
    version: v1.26.4
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 3
