---
- name: Execute sonobouy check mode {{ sonobouy.mode }}
  vars:
    sonobuoy_version: "0.57.1"
    install_dir: "{{ ansible_user_dir }}/.local/bin"
  block:
  - name: Install Sonobuoy
    ansible.builtin.unarchive:
      src: "https://github.com/vmware-tanzu/sonobuoy/releases/download/v{{ sonobuoy_version }}/sonobuoy_{{ sonobuoy_version }}_linux_amd64.tar.gz"
      dest: "{{ install_dir }}"
      mode: '+x'
      remote_src: true
    args:
      creates: "{{ install_dir }}/sonobuoy"
  - name: Run Sonobuoy tests
    ansible.builtin.command: "sonobuoy run --plugin-env=e2e.E2E_PROVIDER=openstack --mode={{ sonobouy.mode }}"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    changed_when: true
  - name: Pause for 7 minutes to be able to retrieve results from sonobuoy
    ansible.builtin.pause:
      seconds: 420
  - name: Sonobuoy status
    ansible.builtin.command: "sonobuoy status"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    register: sonobuoy_status
    changed_when: true
  - name: Retrieve Sonobuoy results
    ansible.builtin.command: "sonobuoy retrieve"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    register: sonobuoy_retrieve_output
    changed_when: true
  - name: Get Sonobuoy results
    ansible.builtin.command: "sonobuoy results {{ sonobuoy_retrieve_output.stdout }}"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    register: sonobuoy_results_output
    changed_when: true
  - name: Delete k8s resources that were generated by a Sonobuoy run
    ansible.builtin.command: "sonobuoy delete --all"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    changed_when: true
  - name: Remove Sonobuoy retrieve file
    ansible.builtin.file:
      path: "{{ sonobuoy_retrieve_output.stdout }}"
      state: absent
