---
- name: Execute sonobouy check mode {{ sonobouy.mode }}
  block:
  - name: Run Sonobuoy tests
    ansible.builtin.command: "sonobuoy run --plugin-env=e2e.E2E_PROVIDER=openstack --mode={{ sonobouy.mode }}"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    changed_when: true
  - name: Pause for 3 minutes to be able to retrieve results from sonobuoy
    ansible.builtin.pause:
      seconds: 180
  - name: Sonobuoy status
    ansible.builtin.command: "sonobuoy status"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    register: sonobuoy_status
    changed_when: true
  - name: Print Sonobuoy status
    ansible.builtin.debug:
      var: sonobuoy_status.stdout_lines
  - name: Retrieve Sonobuoy results
    ansible.builtin.command: "sonobuoy retrieve"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    register: sonobuoy_retrieve_output
    changed_when: true
  - name: Get Sonobuoy results
    ansible.builtin.command: "sonobuoy results {{ sonobuoy_retrieve_output.stdout }}"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    register: sonobuoy_results_output
    changed_when: true
  - name: Print Sonobuoy results
    ansible.builtin.debug:
      var: sonobuoy_results_output.stdout_lines
  - name: Delete k8s resources that were generated by a Sonobuoy run
    ansible.builtin.command: "sonobuoy delete --all"
    environment:
      KUBECONFIG: "{{ cluster_manifest_dir }}/kubeconfig-test-cluster"
    changed_when: true
  - name: Remove Sonobuoy retrieve file
    ansible.builtin.file:
      path: "{{ sonobuoy_retrieve_output.stdout }}"
      state: absent
