openstack-cloud-controller-manager:
  secret:
    enabled: true
    name: cloud-config
    create: false
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
