apiVersion: v2
dependencies:
- alias: metrics-server
  name: metrics-server
  repository: https://kubernetes-sigs.github.io/metrics-server/
  version: 3.12.2
description: Metrics Server
name: openstack-scs-1-32-cluster-addon
type: application
version: v1
