apiVersion: v2
name: cni
description: Cilium CNI for Docker SCS2 cluster stack
type: application
version: 0.1.0
dependencies:
  - name: cilium
    version: 1.19.0
    repository: https://helm.cilium.io/
