metrics-server:
  fullnameOverride: metrics-server
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  service:
    labels:
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: "Metrics-server"

  defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s

  args:
  - --kubelet-insecure-tls
openstack-cloud-controller-manager:
  secret:
    enabled: true
    name: cloud-config
    create: false
  nodeSelector:
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule

openstack-cinder-csi:
  secret:
    enabled: true
    name: cloud-config
    create: false
