apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              node-labels: 'metal3.io/uuid={{"{{"}} ds.meta_data.uuid {{"}}"}}'
            name: '{{"{{"}} ds.meta_data.local_hostname {{"}}"}}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              node-labels: 'metal3.io/uuid={{"{{"}} ds.meta_data.uuid {{"}}"}}'
            name: '{{"{{"}} ds.meta_data.local_hostname {{"}}"}}'
