# This is a clouds.yaml file, which can be used by OpenStack tools as a source
# of configuration on how to connect to a cloud. If this is your only cloud,
# just put this file in ~/.config/openstack/clouds.yaml and tools like
# python-openstackclient will just work with no further config. (You will need
# to add your password to the auth section)
# If you have more than one cloud account, add the cloud entry to the clouds
# section of your existing file and you can refer to them by name with
# OS_CLOUD=openstack or --os-cloud=openstack
clouds:
  openstack:
    auth:
      auth_url: https://demo-api.scs.cloud:5000
      username: "u1234-test"
      project_id: e7622c1048ac4520a2d050ae141e826b
      project_name: "p1234-project"
      user_domain_name: "d1234"
      password: "test"
    region_name: "RegionTest"
    interface: "public"
    identity_api_version: 3
