---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: "ubuntu-capi-image-v1.35.5"
spec:
  cloudCredentialsRef:
    cloudName: "openstack"
    secretName: "openstack"
  managementPolicy: managed
  resource:
    visibility: private
    properties:
      hardware:
        diskBus: scsi
        scsiModel: virtio-scsi
        vifModel: virtio
        qemuGuestAgent: true
        rngModel: virtio
      architecture: x86_64
      minDiskGB: 20
      minMemoryMB: 2048
      operatingSystem:
        distro: ubuntu
        version: "24.04"
    content:
      diskFormat: qcow2
      download:
        url: https://nbg1.your-objectstorage.com/osism/openstack-k8s-capi-images/ubuntu-2404-kube-v1.35/ubuntu-2404-kube-v1.35.5.qcow2
        hash:
          algorithm: sha256
          value: 9ede9a241f14e12f666304d0288934c8fc7ed5ad65b31ed004a7ec0fd53ca32a
