---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: "ubuntu-capi-image-v1.33.6"
spec:
  cloudCredentialsRef:
    cloudName: "openstack"
    secretName: "openstack"
  managementPolicy: managed
  resource:
    properties:
      hardware:
        diskBus: scsi
        scsiModel: virtio-scsi
        vifModel: virtio
        qemuGuestAgent: true
        rngModel: virtio
      architecture: x86_64
      minDiskGB: 20
      minMemoryMB: 2048
      operatingSystem:
        distro: ubuntu
        version: "24.04"
    content:
      diskFormat: qcow2
      download:
        url: https://nbg1.your-objectstorage.com/osism/openstack-k8s-capi-images/ubuntu-2404-kube-v1.33/ubuntu-2404-kube-v1.33.6.qcow2
        hash:
          algorithm: sha256
          value: ff458b22c33fc08eca9ba6635783e9a409b6f0613f577c4acdec554db7e2f6a7
