apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
    machineInfrastructure:
      ref:
        kind: HetznerBareMetalMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HetznerClusterTemplate
      name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
  workers:
    machineDeployments:
    - class: baremetal-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: {{ .Release.Name }}-{{ .Chart.Version }}-baremetal-worker
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HetznerBareMetalMachineTemplate
            name: {{ .Release.Name }}-{{ .Chart.Version }}-baremetal-worker
  variables:
  - name: clusterEndpointHost
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: ""
  - name: clusterEndpointPort
    required: false
    schema:
      openAPIV3Schema:
        type: integer
        default: 443
  - name: clusterLoadBalancerType
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: "lb11"
  - name: clusterLoadBalancerExtraServices
    required: false
    schema:
      openAPIV3Schema:
        type: array
        default: []
        items:
          type: object
          properties:
            protocol:
              type: string
            listenPort:
              type: integer
            destinationPort:
              type: integer
  - name: region
    required: true
    schema:
      openAPIV3Schema:
        type: string
        default: fsn1
  - name: bareMetalWorkerHostSelector
    required: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          matchExpressions:
            type: array
            items:
              type: object
              properties:
                key:
                  type: string
                operator:
                  type: string
                values:
                  type: array
                  items:
                    type: string
          matchLabels:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  - name: bareMetalControlPlaneHostSelector
    required: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          matchExpressions:
            type: array
            items:
              type: object
              properties:
                key:
                  type: string
                operator:
                  type: string
                values:
                  type: array
                  items:
                    type: string
          matchLabels:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  - name: bareMetalWorkerRaidEnabled
    required: false
    schema:
      openAPIV3Schema:
        type: boolean
  - name: bareMetalWorkerRaidLevel
    required: false
    schema:
      openAPIV3Schema:
        type: integer
        default: 1
  - name: bareMetalControlPlaneRaidEnabled
    required: false
    schema:
      openAPIV3Schema:
        type: boolean
  - name: bareMetalControlPlaneRaidLevel
    required: false
    schema:
      openAPIV3Schema:
        type: integer
        default: 1
  - name: rook_ceph_values
    schema:
      openAPIV3Schema:
        type: string
        example: |
          enabled: true
          currentNamespaceOnly: false
        description: "Helm values for Ceph Operator."
  - name: rook_ceph_cluster_values
    schema:
      openAPIV3Schema:
        type: string
        default: "enabled: false"
        example: |
          cephClusterSpec:
            cephVersion:
              image: quay.io/ceph/ceph:v18.2.2
              allowUnsupported: false
        description: "Helm values for Ceph Cluster."
  patches:
  - name: HetznerClusterTemplateGeneral
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: replace
        path: "/spec/template/spec/controlPlaneEndpoint/host"
        valueFrom:
          variable: clusterEndpointHost
      - op: replace
        path: "/spec/template/spec/controlPlaneEndpoint/port"
        valueFrom:
          variable: clusterEndpointPort
      - op: add
        path: "/spec/template/spec/controlPlaneLoadBalancer/type"
        valueFrom:
          variable: clusterLoadBalancerType
      - op: add
        path: "/spec/template/spec/controlPlaneLoadBalancer/extraServices"
        valueFrom:
          variable: clusterLoadBalancerExtraServices
      - op: add
        path: "/spec/template/spec/controlPlaneRegions"
        valueFrom:
          template: {{ `"[{{ .region | quote }}]"` }}
      - op: add
        path: "/spec/template/spec/controlPlaneLoadBalancer/region"
        valueFrom:
          variable: region
  - name: HetznerBareMetalMachineTemplateWorker
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerBareMetalMachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - baremetal-worker
      jsonPatches:
      - op: add
        path: "/spec/template/spec/hostSelector"
        valueFrom:
          variable: bareMetalWorkerHostSelector
      - op: replace
        path: "/spec/template/spec/installImage/swraid"
        valueFrom:
          template: {{ `"{{ if .bareMetalWorkerRaidEnabled }}1{{else}}0{{end}}"` }}
      - op: replace
        path: "/spec/template/spec/installImage/swraidLevel"
        valueFrom:
          variable: bareMetalWorkerRaidLevel
  - name: HetznerBareMetalMachineTemplateControlPlane
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerBareMetalMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/hostSelector"
        valueFrom:
          variable: bareMetalControlPlaneHostSelector
      - op: replace
        path: "/spec/template/spec/installImage/swraid"
        valueFrom:
          template: {{ `"{{ if .bareMetalControlPlaneRaidEnabled }}1{{else}}0{{end}}"` }}
      - op: replace
        path: "/spec/template/spec/installImage/swraidLevel"
        valueFrom:
          variable: bareMetalControlPlaneRaidLevel
  - name: k8s_version
    description: "Sets the k8s version in the preKubeadmCommands according to the version mentioned in spec.topology.version."
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/preKubeadmCommands/0"
        valueFrom:
          template: {{ `"export KUBERNETES_VERSION=$(echo {{ .builtin.cluster.topology.version }} | sed 's/^v//')"` }}
    - selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - baremetal-worker
      jsonPatches:
      - op: add
        path: "/spec/template/spec/preKubeadmCommands/0"
        valueFrom:
          template: {{ `"export KUBERNETES_VERSION=$(echo {{ .builtin.cluster.topology.version }} | sed 's/^v//')"` }}
