apiVersion: v2
dependencies:
- alias: metrics-server
  name: metrics-server
  repository: https://kubernetes-sigs.github.io/metrics-server/
  version: 3.12.1
- alias: tigera-operator
  name: tigera-operator
  repository: https://docs.tigera.io/calico/charts
  version: v3.28.1
- alias: hcloud-cloud-controller-manager
  name: hcloud-cloud-controller-manager
  repository: https://charts.hetzner.cloud
  version: 1.20.0
- alias: rook-ceph
  name: rook-ceph
  repository: https://charts.rook.io/release
  version: v1.14.9
  condition: rook-ceph.enabled,rook-ceph-cluster.enabled
- alias: rook-ceph-cluster
  name: rook-ceph-cluster
  repository: https://charts.rook.io/release
  version: v1.14.9
  condition: rook-ceph-cluster.enabled
- alias: cert-manager
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.15.2
- alias: ingress-nginx
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.11.1
- alias: prometheus-operator-crds
  name: prometheus-operator-crds
  repository: https://prometheus-community.github.io/helm-charts
  version: 13.0.2
name: hetzner-baremetal-1-30-cluster-addon
type: application
version: v1
