apiVersion: v2
dependencies:
- alias: metrics-server
  name: metrics-server
  repository: https://kubernetes-sigs.github.io/metrics-server/
  version: 3.12.1
- alias: cilium
  name: cilium
  repository: https://helm.cilium.io/
  version: 1.15.6
- alias: ccm-hetzner
  name: ccm-hetzner
  repository: https://charts.syself.com
  version: 1.1.15
- alias: rook-ceph
  name: rook-ceph
  repository: https://charts.rook.io/release
  version: v1.14.7
  condition: rook-ceph.enabled,rook-ceph-cluster.enabled
- alias: rook-ceph-cluster
  name: rook-ceph-cluster
  repository: https://charts.rook.io/release
  version: v1.14.7
  condition: rook-ceph-cluster.enabled
name: hetzner-baremetal-1-30-cluster-addon
type: application
version: v1
