metrics-server:
  fullnameOverride: metrics-server

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  service:
    labels:
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: "Metrics-server"

hcloud-cloud-controller-manager:
  robot:
    enabled: true
  env:
    HCLOUD_TOKEN:
      valueFrom:
        secretKeyRef:
          name: hetzner
          key: hcloud
    ROBOT_USER:
      valueFrom:
        secretKeyRef:
          name: hetzner
          key: robot-user
    ROBOT_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: hetzner
          key: robot-password

rook-ceph:
  enableDiscoveryDaemon: true
rook-ceph-cluster:
  operatorNamespace: kube-system
  toolbox:
    enabled: true
  cephClusterSpec:
    mgr:
      modules:
      - name: rook
        enabled: true

cert-manager:
  fullnameOverride: cert-manager
  crds:
    enabled: true

ingress-nginx:
  fullnameOverride: ingress-nginx
