apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Values.prefix }}-{{ .Values.testcluster_name }}-control-plane-{{ .Values.control_plane_machine_gen}}
  namespace: {{ .Values.testcluster_name }}
spec:
  template:
    spec:
      cloudName: {{ .Values.prefix }}-{{ .Values.testcluster_name }}
      flavor: {{ .Values.controller_flavor }}
      identityRef:
        kind: Secret
        name: {{ .Values.testcluster_name }}-cloud-config
      image: ubuntu-capi-image-v1.27.5
      securityGroups:
{{- if .Values.openstack_security_groups }}
{{- range $.Values.openstack_security_groups }}
        - name: {{ . }}
{{- end}}
{{- else }}
        - name: {{ .Values.prefix }}-allow-ssh
        - name: {{ .Values.prefix }}-allow-icmp
        - name: {{ .Values.prefix }}-{{ .Values.testcluster_name }}-cilium
{{- end}}
      # serverGroupID left blank for now
      sshKeyName: {{ .Values.prefix }}-keypair