apiVersion: clusteraddonconfig.x-k8s.io/v1alpha1
clusterAddonVersion: clusteraddons.clusterstack.x-k8s.io/v1alpha1
addonStages:
  AfterControlPlaneInitialized:
    - name: cni
      action: apply
    - name: metrics-server
      action: apply
  BeforeClusterUpgrade:
    - name: cni
      action: apply
    - name: metrics-server
      action: apply
