apiVersion: v2
name: cni
description: Cilium CNI for Docker bryggan cluster stack
type: application
version: 0.1.0
dependencies:
  - name: cilium
    version: 1.19.1
    repository: https://helm.cilium.io/
