apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-default-worker
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: unix:///var/run/containerd/containerd.sock
          kubeletExtraArgs:
            - name: eviction-hard
              value: "nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%"
            - name: fail-swap-on
              value: "false"
