apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: crs-{{ include "cloud_name" . }}-secret
spec:
  strategy: "Reconcile"
  clusterSelector:
    matchLabels:
      managed-secret: cloud-config
  resources:
    - name: {{ include "cloud_name" . }}-workload-cluster-secret
      kind: Secret
