apiVersion: v1
data:
  cloud-config-secret: {{ include "cloud-config" . | b64enc }}
kind: Secret
metadata:
  name: {{ include "cloud_name" . }}-workload-cluster-secret
type: addons.cluster.x-k8s.io/resource-set 
