{{- if .Values.cilium.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: testing
  name: cilium-operator
  namespace: {{.Release.Namespace}}
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      metricRelabelings:
        - action: replace
          replacement: testing
          targetLabel: cluster
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
  targetLabels:
    - io.cilium/app
{{- end }}