apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
        name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtClusterTemplate
      name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: {{ .Release.Name }}-{{ .Chart.Version }}-default-worker
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
            kind: KubevirtMachineTemplate
            name: {{ .Release.Name }}-{{ .Chart.Version }}-default-worker
  variables:
  - name: image
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: "quay.io/capk/ubuntu-2204-container-disk:v1.29.5"
        example: "quay.io/capk/ubuntu-2204-container-disk:v1.29.5"
        description: "Container image used by worker and control plane nodes"
  patches:
  - name: image
    description: Overrides image data for worker and control plane nodes
    enabledIf: {{ `"{{ if .image }}true{{end}}"` }}
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
        matchResources:
          controlPlane: true
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: replace
        path: /spec/template/spec/virtualMachineTemplate/spec/template/spec/volumes
        valueFrom:
          template: |
            - name: containervolume
              containerDisk:
                image: '{{"{{"}} .image {{"}}"}}'
