values: |
  metrics-server:
    commonLabels:
      domain: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
      clusterAddonVersion: "v2"
  yawol-controller:
    yawolFloatingID: "{{ .InfraCluster.status.externalNetwork.id }}"
    yawolNetworkID: "{{ .InfraCluster.status.network.id }}"
    yawolAPIHost: "{{ printf "https://%s:%d" .Cluster.spec.controlPlaneEndpoint.host .Cluster.spec.controlPlaneEndpoint.port }}"
    {{- range .Cluster.spec.topology.variables }}
    {{- if eq .name "yawol_flavor_id" }}
    yawolFlavorID: {{ .value }}
    {{- else if eq .name "yawol_image_id" }}
    yawolImageID: {{ .value }}
    {{- end }}
    {{- end }}
  openstack-cloud-controller-manager:
    cloudConfig:
      loadBalancer:
      {{- if or (eq .workload_loadbalancer "none") (eq .workload_loadbalancer "yawol") }}
        enabled: false
      {{ else if eq .workload_loadbalancer "octavia-amphora" }}
        enabled: true
        lb-provider: amphora
      {{ else if eq .workload_loadbalancer "octavia-ovn" }}
        enabled: true
        lb-provider: ovn
      {{- end }}