values: |
  metrics-server:
    commonLabels:
      domain: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
      clusterAddonVersion: "v2"
  yawol-controller:
    yawolFloatingID: "{{ .InfraCluster.status.externalNetwork.id }}"
    yawolNetworkID: "{{ .InfraCluster.status.network.id }}"
    yawolAPIHost: "{{ printf "https://%s:%d" .Cluster.spec.controlPlaneEndpoint.host .Cluster.spec.controlPlaneEndpoint.port }}"
