---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: deny-egress-to-metadata-service
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - all
  egressDeny:
    - toCIDR:
        - 169.254.169.254/32
