apiVersion: v1
data:
  cloud-config-secret: {{ include "cloud-config" . | b64enc }}
kind: Secret
metadata:
  name: openstack-workload-cluster-secret
  namespace: {{ include "namespaceName" . }}
type: addons.cluster.x-k8s.io/resource-set 
