apiVersion: csctl.clusterstack.x-k8s.io/v1alpha1
config:
  kubernetesVersion: v1.35.1
  clusterStackName: scs2
  provider:
    type: docker
    apiVersion: docker.csctl.clusterstack.x-k8s.io/v1alpha1
