apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackClusterTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
spec:
  template:
    spec:
      identityRef:
        name: {{ .Values.identityRef.name }}
        cloudName: {{ .Values.identityRef.cloudName }}
      disableAPIServerFloatingIP: true
      apiServerLoadBalancer:
        enabled: false
      managedSecurityGroups:
        allowAllInClusterTraffic: true
      managedSubnets:
      - cidr: {{ .Values.node_cidr }}
        dnsNameservers:
        {{- range .Values.dns_nameservers }}
        - {{ . }}
        {{- end }}
      externalNetwork:
        id: {{ .Values.external_id }}
