---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: "{{ .Values.images.worker.name }}"
spec:
  cloudCredentialsRef:
    cloudName: "{{ .Values.identityRef.cloudName }}"
    secretName: "{{ .Values.identityRef.name }}"
  managementPolicy: managed
  resource:
    properties:
      diskBus: "scsi"
      scsiModel: "virtio-scsi"      
    content:
      diskFormat: qcow2
      download:
        url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube-v1.30/ubuntu-2204-kube-v1.30.11.qcow2
        hash:
          algorithm: sha256
          value: 0ee13cc5662e3dd3c547d09b01a0604df19cf15598e1142ddb7fc4a8ce58ee58
