---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: "{{ .Values.images.worker.name }}"
spec:
  cloudCredentialsRef:
    cloudName: "{{ .Values.identityRef.cloudName }}"
    secretName: "{{ .Values.identityRef.name }}"
  managementPolicy: managed
  resource:
    properties:
      diskBus: "scsi"
      scsiModel: "virtio-scsi"      
    content:
      diskFormat: qcow2
      download:
        url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube-v1.31/ubuntu-2204-kube-v1.31.7.qcow2
        hash:
          algorithm: sha256
          value: 16bf3f748ec74bfc58e98e7566012b64f9b65a7fc4871101e5d9c5d8daa7d350
