apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
              bind-address: 0.0.0.0
              secure-port: 10257
          scheduler:
            extraArgs:
              bind-address: 0.0.0.0
              secure-port: 10259
          etcd:
            local:
              dataDir: /var/lib/etcd
              extraArgs:
                listen-metrics-urls: http://0.0.0.0:2381              
                auto-compaction-mode: periodic
                auto-compaction-retention: 8h
                election-timeout: "2500"
                heartbeat-interval: "250"
                snapshot-count: "6400"
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{"{{"}} instance_id {{"}}"}}'
            name: '{{"{{"}} local_hostname {{"}}"}}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{"{{"}} instance_id {{"}}"}}'
            name: '{{"{{"}} local_hostname {{"}}"}}'
