apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
spec:
  template:
    spec:
      flavor: {{ .Values.controller_flavor }}
      identityRef:
        cloudName: {{ .Values.identityRef.cloudName }}
        name: {{ .Values.identityRef.name }}
      image:
        filter:
          name: {{ .Values.images.controlPlane.name }}
