apiVersion: v2
dependencies:
- alias: metrics-server
  name: metrics-server
  repository: https://kubernetes-sigs.github.io/metrics-server/
  version: 3.12.0
- alias: cilium
  name: cilium
  repository: https://helm.cilium.io/
  version: 1.15.2
- alias: openstack-cloud-controller-manager
  name: openstack-cloud-controller-manager
  repository: https://kubernetes.github.io/cloud-provider-openstack
  version: 2.29.1
- alias: openstack-cinder-csi
  name: openstack-cinder-csi
  repository: https://kubernetes.github.io/cloud-provider-openstack
  version: 2.29.0
name: openstack-alpha-1-29-cluster-addon
type: application
version: v2
