apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}
spec:
  template:
    spec:
      flavor: {{ .Values.worker_flavor }}
      identityRef:
        name: {{ default "openstack" .Values.identityRef.name }}
        cloudName: {{ default "openstack" .Values.identityRef.cloudName }}
      image:
        filter:
          name: placeholder
