---
# This Play should be used on PRs against release branches to upload Release Assets to SCS Registry
- name: "Create Chore Branches and PRs"
  hosts: "all"
  vars:
    install_dir: "{{ ansible_user_dir }}/.local/bin"
    github_token: ""
  environment:
    PATH: "{{ install_dir }}:{{ ansible_env.PATH }}"
  tasks:
    - name: Install just
      ansible.builtin.unarchive:
        src: "https://github.com/casey/just/releases/download/{{ just_version }}/just-{{ just_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ install_dir }}"
        extra_opts: "--strip-components=1"
        mode: "+x"
        remote_src: true
      args:
        creates: "{{ install_dir }}/just"
    - name: "Ensure just env file"
      ansible.builtin.copy:
        src: "just.env.example"
        dest: "just.env"
        mode: preserve
    - name: "Set Enviroments variables for just"
      ansible.builtin.lineinfile:
        path: "just.env"
        regexp: '^GH_TOKEN='
        line: "GH_TOKEN={{ github_token }}"
    - name: "Build Versions"
      ansible.builtin.command: "just build-versions"
      changed_when: false
    - name: "Create Chore PRs"
      ansible.builtin.command: "just git-chore-branches-all"
      changed_when: false
