FROM ubuntu:22.04 AS worker-base

RUN mkdir /scripts

COPY ./scripts/ /scripts

WORKDIR /scripts

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       curl \
       gnupg \
       apt-transport-https \
       ca-certificates \
       software-properties-common \
    && rm -rf /var/lib/apt/lists/*

RUN /scripts/base.sh \
    && /scripts/kubernetes.sh \
    && /scripts/cleanup.sh
