cilium:
  namespaceOverride: kube-system
  tls:
    secretsNamespace:
      name: "kube-system"
  sessionAffinity: true
  sctp:
    enabled: true
  ipam:
    mode: "kubernetes"
  kubeProxyReplacement: "true"
  gatewayAPI:
    enabled: true
    #gatewayClass: true
    secretsNamespace:
      name: "kube-system"
