apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cspo.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cspo
    app.kubernetes.io/part-of: cspo
    control-plane: controller-manager
  {{- include "cspo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "cspo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "cspo.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /manager
        - -source
        - {{ .Values.controllerManager.manager.source }}
        env:
        {{- if eq .Values.controllerManager.manager.source "github" }}
        - name: GIT_PROVIDER
          valueFrom:
            secretKeyRef:
              key: git-provider
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        - name: GIT_ORG_NAME
          valueFrom:
            secretKeyRef:
              key: git-org-name
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        - name: GIT_REPOSITORY_NAME
          valueFrom:
            secretKeyRef:
              key: git-repo-name
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        - name: GIT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: git-access-token
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        {{- else }}
        - name: OCI_REGISTRY
          valueFrom:
            secretKeyRef:
              key: oci-registry
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        - name: OCI_REPOSITORY
          valueFrom:
            secretKeyRef:
              key: oci-repository
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        - name: OCI_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: oci-access-token
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        - name: OCI_USERNAME
          valueFrom:
            secretKeyRef:
              key: oci-username
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        - name: OCI_PASSWORD
          valueFrom:
            secretKeyRef:
              key: oci-password
              name: {{ include "cspo.fullname" . }}-cluster-stack-variables
        {{- end }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      - args: {{- toYaml .Values.controllerManager.kubeRbacProxy.args | nindent 8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.kubeRbacProxy.image.repository }}:{{ .Values.controllerManager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {{- toYaml .Values.controllerManager.kubeRbacProxy.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.controllerManager.kubeRbacProxy.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: {{ include "cspo.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
