apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cspo.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cspo
    app.kubernetes.io/part-of: cspo
  {{- include "cspo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}