apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.prefix }}-{{ .Values.testcluster_name }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{"{{"}}instance_id{{"}}"}}'
          name: '{{"{{"}}local_hostname{{"}}"}}'
