apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: {{ .Values.testcluster_name }}-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
          dns:
            imageRepository: registry.k8s.io/coredns
          etcd:
            local:
              dataDir: /var/lib/etcd
              extraArgs:
                auto-compaction-mode: periodic
                auto-compaction-retention: 8h
                election-timeout: "2500"
                heartbeat-interval: "250"
                snapshot-count: "6400"
          imageRepository: registry.k8s.io
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{"{{"}}instance_id{{"}}"}}'
            name: '{{"{{"}}local_hostname{{"}}"}}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{"{{"}}instance_id{{"}}"}}'
            name: '{{"{{"}}local_hostname{{"}}"}}'
